CREATE DATABASE IF NOT EXISTS lestoplay2025;
USE lestoplay2025;

CREATE TABLE IF NOT EXISTS CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (50),
	EMAIL VARCHAR (50),
	SENHA VARCHAR (50),
	TELEFONE VARCHAR (20)
);

CREATE TABLE IF NOT EXISTS TIPOESPORTE (
	IDESPORTE INT PRIMARY KEY AUTO_INCREMENT,
	MODALIDADE VARCHAR (50)
);

CREATE TABLE IF NOT EXISTS EQUIPAMENTO (
	IDEQUIP INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (50),
	QUANTIDADE INT
);

CREATE TABLE IF NOT EXISTS quadras (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    localizacao VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS (
	IDRESERVA INT PRIMARY KEY AUTO_INCREMENT,
	HORARIO TIME,
	DATA DATE,
	PRECO DECIMAL (10, 2),
	STATUS VARCHAR (20),
	IDCLIENTE INT,
	IDESPORTE INT,
	IDEQUIP INT,
	IDQUADRA INT,
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	FOREIGN KEY (IDESPORTE) REFERENCES TIPOESPORTE(IDESPORTE),
	FOREIGN KEY (IDEQUIP) REFERENCES EQUIPAMENTO(IDEQUIP),
	FOREIGN KEY (IDQUADRA) REFERENCES quadras(id)
);

-- Inserir dados de exemplo para as novas tabelas
INSERT INTO CLIENTE (NOME, EMAIL, SENHA, TELEFONE) VALUES
("João Silva", "joao@example.com", "12345", "(11) 98765-4321"),
("Maria Souza", "maria@example.com", "abcde", "(21) 99876-5432");

INSERT INTO TIPOESPORTE (MODALIDADE) VALUES
("Futebol de Areia"),
("Vôlei de Praia"),
("Beach Tennis");

INSERT INTO EQUIPAMENTO (NOME, QUANTIDADE) VALUES
("Bola de Vôlei", 5),
("Rede de Beach Tennis", 3),
("Kit de Futebol de Areia", 2);

INSERT INTO quadras (nome, localizacao) VALUES
("Quadra Principal", "Rua da Praia, 100"),
("Quadra Secundária", "Avenida do Sol, 250");

-- Inserir algumas reservas de exemplo (ajuste os IDs conforme o auto_increment)
INSERT INTO RESERVAS (HORARIO, DATA, PRECO, STATUS, IDCLIENTE, IDESPORTE, IDEQUIP, IDQUADRA) VALUES
("10:00:00", "2025-09-01", 50.00, "ativa", 1, 1, 1, 1),
("14:00:00", "2025-09-01", 60.00, "ativa", 2, 2, 2, 2),
("16:00:00", "2025-09-02", 55.00, "ativa", 1, 3, 3, 1);

